config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'user#index'
  resources :user, only: %i[index show destroy] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy] 
      resources :likes, only: %i[new create destroy]
    end
 end
 namespace :api do
  resources :users, only: [] do
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

end

app/models/ability.rb
# rubocop:disable all
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    def initialize(user)
    user ||= User.new
      if user.role == 'admin'
        can :manage, :all
      else
        can :destroy, Post do |post|
          post.author == user
        end
        can :destroy, Comment do |comment|
          comment.author == user
        end
        can :create, Post
        can :create, Comment
        can :read, :all
      end
    end
  end
end
#
# The first argument to `can` is the action you are giving the user
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on.
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, published: true
#
# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter_post
  def update_comments_counter_post
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter_post
  def update_likes_counter_post
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_post_counter
  def update_post_counter
    author.increment!(:post_counter)
  end

  def most_recent_comments
    Comment.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable,
         :jwt_authenticatable, jwt_revocation_strategy: Denylist

  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, allow_blank: false
  validates :post_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  ROLES = %i[admin default].freeze

  def admin?
    role == 'admin'
  end

  def most_recent_post
    Post.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]

  def index
    posts = Post.find(params[:post_id])
    comments = posts.comments.includes(:author)
    render json: comments
  end

  def create
    posts = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.author_id = current_user.id
    comment.post_id = posts.id

    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :bio, :photo, :password, :post_counter, :role)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by(id: params[:post_id])
    @comment.author_id = current_user.id
    @comment.post_id = @post.id

    if @comment.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: ':( Cannot Create comment retry again :('
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @post.decrement!(:comments_counter)
    @comment.destroy
    redirect_to user_post_path(user_id: @post.author_id, post_id: @post.id), notice: 'Deleted Comment'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find_by(id: params[:post_id])
    @like = @post.likes.new(author_id: current_user.id, post_id: @post)

    if @like.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      render :new, alert: ':( Cannot Add A Like retry again :('
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments.includes(:author)

    respond_to do |format|
      format.html
      format.json do
        if current_user.id == params[:id].to_i
          render json: @post.comments
        else
          render html: 'You are not authorized'
        end
      end
    end
  end

  def new
    @post = Post.new
  end

  def create
    @current_user = User.find_by(id: params[:user_id])
    @post = @current_user.posts.new(post_params)
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      redirect_to user_path(id: @post.author_id)
    else
      render :new, alert: ':( Cannot Create post retry again :('
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @user.decrement!(:post_counter)
    @post.destroy
    redirect_to user_posts_path, notice: 'Deleted Post'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.most_recent_post
    respond_to do |format|
      format.html
      format.json do
        if current_user.id == params[:id].to_i
          render json: @user.posts
        else
          render html: 'You are not authorized'
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="commentsFormContainer">
<h1 class="create-title">Create A New Comment</h1>
<%= form_with model: @comment, url: user_post_comments_path, class: "comment" do |form| %>
<div class="post-form">
<%= form.label :text, class: "ptitle" %><br>
<%= form.text_area :text, class: "ptitlebox", cols: 30, rows: 5 %> <br>
<%= form.submit "Submit Comment", class: "comment-btn" %>
</div>
<% end %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Blog Post', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= button_to 'logout', destroy_user_session_path, data: {turbo: false}, method: :delete, class: "btn btn-danger" %>
        </li>
        <li class="nav-item text-secondary mx-5">
          Logged in as 
          <strong><%= current_user.email %></strong>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BlogApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if alert %>
    <div class="alert alert-danger">
      <%= alert%>
    </div>
    <% end %>
    <% if notice %>
    <div class="alert alert-success">
      <%= notice%>
    </div>
    <% end %>
    <% if user_signed_in? %>
      <%= render 'home/header' %>
      <%# <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      <% end %>

    <%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts_index_view">
    <div class="post_show">
    <div> <img src= "<%= @user.photo %>" class="py-2 userImage"> </div>

    <div class = "borders" >
      <h3 class="user_name"><%= @user.name %></h3>
      <span class="num" >
        Number of posts: <%= @user.post_counter %>
      </span>
    </div>
  </div>
  <div>

    <div class="link-new-post">
    <%= link_to "Create A New Post", new_user_post_path, class: "new-btn" %>
    </div>
    <% Post.all.each do |post| %>
      <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
      <div class="post-content">
        <div class="ptitle"> Post : <%= post.title%></div>
        <div class="ptext"><%= post.text%></div>
        <div class="pcount">
        Comments: <%= post.comments_counter%>
        Likes: <%= post.likes_counter%>
    </div>
    <% if can? :destroy, post %>
        <%= button_to "Delete Post", user_post_path(post.author.id, post.id), method: :delete, class: "delete-btn" %>
        <% end %>
        </div>
    <div class="comments-container"> 
     <% post.most_recent_comments.each do |comments| %>
     <div class="comments">
     <div class="comments-context">
     <%= comments.author.name %> :  <%= comments.text %>
     </div>
     </div>
     <% end %>
      <% end %>
      </div>
    <% end %>
  </div>
     <div class="all-posts"><%= link_to "Pagination", user_posts_path(user_id: @user.id), class: "posts-btn" %></div>

app/views/posts/new.html.erb
<div class="postsFormContainer">
<h1 class="create-title">Create A New Post</h1>
<%= form_with model: Post, url: user_posts_path, data: {turbo: false}, class: "post" do |form| %>
<div class="post-form">
<%= form.label :title, class: "ptitle" %><br>
<%= form.text_field :title, class: "ptitlebox" %> <br>
<%= form.label :text, class: "ptitle" %><br>
<%= form.text_area :text, class: "ptitlebox", cols: 30, rows: 5 %> <br>
<%= form.submit "Submit Post", class: "posts-btn" %>
</div>
<% end %>
</div>

app/views/posts/post.html.erb
<h1>Post detail<h1>

app/views/posts/posts.html.erb
<h1>User Post<h1>

app/views/posts/show.html.erb
<div class="show_post_view">
 <div class="post-content">
        <div class="ptitle"> Post : <%= @post.title%> by <%= @post.author.name %></div>
        <div class="ptext"><%= @post.text%></div>
         <div class="pcountLikes">
        Comments: <%= @post.comments_counter%>
        Likes: <%= @post.likes_counter%>
    </div>
    <div class="add-comment-container">
    <% if user_signed_in? %>
        <%= link_to "Add A New Comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id), class: "new-comment-btn" %>
        <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
        <%= form.submit "Add Like", class: "like-btn" %>
        <% end %>
         <% if can? :destroy, @post %>
        <%= button_to "Delete Post", user_post_path(@post.author.id, @post.id), method: :delete, class: "delete-btn" %>
        <% end %>
    <% end %>
    </div>
    </div>
     <div class="comments-container"> 
     <% @comments.each do |comments| %>
     <div class="comments">
     <div class="comments-context">
     <%= comments.author.name %> :  <%= comments.text %>
     </div>
      <% if can? :destroy, comments %>
      <%= button_to "Delete Comment", user_post_comment_path(user_id: comments.author.id, post_id: comments.post.id, id: comments.id), method: :delete, class: "delete-btn" %>
      <% end %>
     </div>
     <% end %>
 </div>

app/views/user/index.html.erb
<div class="user_index_container">
<h1 class="welcome">Welcome to the Users Page. Below is the list of users.</h1>
    <% User.all.each do |user| %>
    <div class="user-container">
    <div  class = "user_profile col-4">
      <div> <img src= "<%= user.photo %>" class="py-2 userImage"> </div>
    <div class="borders col-8">
    <%= link_to user do %>
    <div class="user-name"><%= user.name %></div>
     <% end %>
    <div class="num">Number Of Posts: <%= user.post_counter %></div>
    </div>
    </div>
    <% end %>
</div>

app/views/user/show.html.erb
<div class="user_show_container">
  <div  class= "show_profile">
   <div> <img src= "<%= @user.photo %>" class="py-2 userImage"> </div>
    <div class= "borders">
      <h3 class = "user_name"><%= @user.name %></h3>
      <span class="num">
        Number of posts: <% if @user.post_counter.to_i > 0 %> <%= @user.post_counter %> <% else %>
        <%= 0 %> <% end %>
      </span>
    </div>
  </div>
  <div class = "border" >
    <h3 class="bio">Bio:</h3>
    <p class = "post_show_title"><%= @user.bio %></p>
  </div>
  <div >
    <% @user.most_recent_post.each do |post| %>
    <div class = "border">
      <h5 class = "post_show_id">Post #<%= @user.post_counter %></h5>
      <h4 class = "post_show_titles"><%= post.title %></h4>
      <p class = "post_show_text"><%= post.text %></p>
      <% if post.comments_counter.to_i > 0 %>
      <span  >Comments: <%= post.comments_counter %></span>
      <% else %>
      
      <span >Comments: <%= 0 %></span>
      <% end %> <% if post.likes_counter.to_i > 0 %>
      <span>Likes:<%= post.likes_counter %></span>
      <% else %>
      <span >Likes: <%= 0 %></span>
    </div>
    </div>
      <% end %> <% end %>
  </div>
  <div class="btn"><%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "posts-btn" %></div>

</div>